/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdc_xercesandroid_MyXerces */

#ifndef _Included_com_gdc_xercesandroid_MyXerces
#define _Included_com_gdc_xercesandroid_MyXerces
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdc_xercesandroid_MyXerces
 * Method:    getTestStrFromXerces
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gdc_xercesandroid_MyXerces_getTestStrFromXerces
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
